# Generated by Django 5.1.4 on 2025-02-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsale', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerCar',
        ),
        migrations.DeleteModel(
            name='CustomerPurchase',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
